// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtzkfrstuqxfbelwxpog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0emtmcnN0dXF4ZmJlbHd4cG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjA5MzksImV4cCI6MjA3NDMzNjkzOX0.8-bgqhfvlId3OdGryIYLm858n5wg1P4HW7L6RFbDWWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});